---
title: "Fisheries Analysis"
author: "Jerry Ngai"
date: "1/28/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE)

library(tidyverse) # install.packages("tidyverse")
library(here) # install.packages("here")
library(janitor) # install.packages("janitor")
library(paletteer) # install.packages("paletteer")

```

Read in noaa_landings.csv

```{r}
us_landings = read_csv(here("data", "noaa_landings.csv"), 
                       na = c("no data"))
```

Clean up column names:

```{r}
salmon_clean <- us_landings %>% 
  clean_names() %>%
  mutate(afs_name = str_to_lower(afs_name)) %>% 
  mutate(dollars_numeric = parse_number(dollars_usd)) %>% 
  filter(str_detect(afs_name, pattern = "salmon")) %>% 
  separate(afs_name, c("group", "subgroup"), sep = ", ") %>%           # identifies identifier as comma + space
  drop_na(dollars_numeric)
```

### Annual total value by salmon subgroup

```{r}
salmon_us_annual <-salmon_clean %>% 
  group_by(year, subgroup) %>%
  summarize(total_value = sum(dollars_numeric))
```

### Make a line graph

```{r}
ggplot(salmon_us_annual, aes(x = year,
                             y = total_value,
                             group = subgroup)) +
  geom_line(aes(color = subgroup)) +
  theme_bw() +
  labs(x = "Year",
       y = "US commercial salmon value (USD)",
       title = "Annual US Salmon Landings") +
  scale_color_paletteer_d("colorblindr::OkabeIto")

# colorblindr	OkabeIto

```

